// Standalone Landing Page Files
// These are the files that will be exported as ZIP

export const generatePixelsJS = (pixels: { facebook?: string; tiktok?: string; ga?: string }) => {
    return `// Pixel Tracking Scripts
// Auto-generated by Admin Panel

// Facebook Pixel
${pixels.facebook ? `
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '${pixels.facebook}');
fbq('track', 'PageView');

// Track custom events
window.trackPixelEvent = function(event, data) {
  if (typeof fbq !== 'undefined') {
    fbq('track', event, data);
  }
};
` : '// Facebook Pixel not configured\nwindow.trackPixelEvent = function() {};'}

// TikTok Pixel
${pixels.tiktok ? `
!function (w, d, t) {
  w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var i="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=i,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};var o=document.createElement("script");o.type="text/javascript",o.async=!0,o.src=i+"?sdkid="+e+"&lib="+t;var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(o,a)};

  ttq.load('${pixels.tiktok}');
  ttq.page();
}(window, document, 'ttq');
` : '// TikTok Pixel not configured'}

// Google Analytics
${pixels.ga ? `
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${pixels.ga}');

var gaScript = document.createElement('script');
gaScript.async = true;
gaScript.src = 'https://www.googletagmanager.com/gtag/js?id=${pixels.ga}';
document.head.appendChild(gaScript);
` : '// Google Analytics not configured'}

console.log('[Pixels] Initialized successfully');
`;
};

export const generateREADME = (domain: string) => {
    return `# Standalone Landing Page - Kurulum Rehberi

## Dosyalar
- \`index.html\` - Ana sayfa
- \`config.js\` - Konfigürasyon
- \`api-client.js\` - API bağlantısı
- \`pixels.js\` - Pixel tracking
- \`.htaccess\` - SEO ve caching

## Kurulum Adımları

### 1. Dosyaları Yükleyin
Tüm dosyaları web hosting'inizin kök dizinine yükleyin:
- cPanel File Manager
- FTP (FileZilla, vb.)
- SSH/SFTP

### 2. Domain Ayarları
DNS ayarlarınızda:
\`\`\`
Type: A Record
Name: @ (veya subdomain)
Value: [Hosting IP Adresiniz]
\`\`\`

### 3. SSL Sertifikası
HTTPS zorunludur!
- cPanel'den Let's Encrypt ücretsiz SSL
- Veya Cloudflare kullanın

### 4. Admin Panelde Domain Ekle
1. Admin Panel → Domains
2. Domain: \`${domain}\`
3. Ürünü ve şablonu seç
4. Kaydet

### 5. Test
\`${domain}\` adresine gidin ve sayfa yüklenip yüklenmediğini kontrol edin.

## Sorun Giderme

**Sayfa açılmıyor:**
- DNS propagate olması 5-60 dakika sürebilir
- \`.htaccess\` dosyası doğru yüklendi mi?
- SSL sertifikası aktif mi?

**Ürün bilgileri gelmiyor:**
- Admin panelde domain tanımlı mı?
- \`config.js\` içinde ADMIN_PANEL_URL doğru mu?
- Browser console'da hata var mı?

**Sipariş oluşturulmuyor:**
- CORS hatası var mı?
- Admin panel API'leri erişilebilir mi?
- Form validation geçiyor mu?

## Destek
Admin panel → Settings → Support

---
© 2024 - Auto-generated by Admin Panel
`;
};

export const generateHTACCESS = () => {
    return `# Landing Page - SEO & Performance Optimization

# Force HTTPS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

# Gzip Compression
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
  AddOutputFilterByType DEFLATE application/javascript application/json
</IfModule>

# Browser Caching
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresDefault "access plus 1 month"
  
  # HTML (no cache)
  ExpiresByType text/html "access plus 0 seconds"
  
  # CSS and JavaScript
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType application/javascript "access plus 1 year"
  
  # Images
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 year"
</IfModule>

# Security Headers
<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "SAMEORIGIN"
  Header set X-XSS-Protection "1; mode=block"
</IfModule>

# Disable Directory Browsing
Options -Indexes

# Custom Error Pages
ErrorDocument 404 /index.html
`;
};
